# Generated by Django 3.1.7 on 2022-01-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20220126_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(default=1, upload_to='photos/%Y/%m/'),
            preserve_default=False,
        ),
    ]
