# Generated by Django 3.1.7 on 2022-01-23 02:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('is_featured', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/')),
                ('Color', models.ManyToManyField(blank=True, null=True, to='category.Color')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.category')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product')),
                ('sizes', models.ManyToManyField(blank=True, null=True, to='category.Size')),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
    ]
