# Generated by Django 3.1.7 on 2022-01-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220124_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='solt',
            field=models.IntegerField(default=0),
        ),
    ]
