# Generated by Django 3.1.7 on 2022-01-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_solt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='solt',
            new_name='sold',
        ),
    ]
