// Authentication JWT 

export const SIGNUP_OK = 'SIGNUP_OK';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const LOGIN_OK = "LOGIN_OK"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const USER_LOADED_OK = "USER_LOADED_OK"
export const USER_LOADED_FAIL = "USER_LOADED_FAIL"

export const ACTIVATION_OK = "ACTIVATION_OK"
export const ACTIVATION_FAIL = "ACTIVATION_FAIL"

export const SET_AUTH_LOADING="SET_AUTH_LOADING"
export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';

export const AUTHENTICATED_OK = "AUTHENTICATED_OK"
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL"

export const REFRESH_OK = "REFRESH_OK"
export const REFRESH_FAIL = "REFRESH_FAIL"

export const LOGOUT = 'LOGOUT';

export const RESET_PASSWORD_OK="RESET_PASSWORD_OK"
export const RESET_PASSWORD_FAIL="RESET_PASSWORD_FAIL"

export const RESET_PASSWORD_CONFIRM_OK="RESET_PASSWORD_CONFIRM_OK"
export const RESET_PASSWORD_CONFIRM_FAIL="RESET_PASSWORD_CONFIRM_FAIL"

// Alerts

export const SET_ALERT="SET_ALERT"
export const REMOVE_ALERT="REMOVE_ALERT"

// Categories

export const GET_CATEGORIES_OK = 'GET_CATEGORIES_OK';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';

//colors

export const GET_COLOR_OK = 'GET_COLOR_OK';
export const GET_COLOR_FAIL = 'GET_COLOR_FAIL';

//sizes

export const GET_SIZE_OK = 'GET_SIZE_OK';
export const GET_SIZE_FAIL = 'GET_SIZE_FAIL';

// Products 

export const GET_PRODUCT_OK = "GET_PRODUCT_OK"
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL"

export const GET_PRODUCTS_HOME_OK = "GET_PRODUCTS_HOME_OK"
export const GET_PRODUCTS_HOME_FAIL = "GET_PRODUCTS_HOME_FAIL"


export const GET_PRODUCTS_OK = 'GET_PRODUCTS_OK';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';

export const GET_PRODUCTS_BY_ARRIVAL_OK = 'GET_PRODUCTS_BY_ARRIVAL_OK';
export const GET_PRODUCTS_BY_ARRIVAL_FAIL = 'GET_PRODUCTS_BY_ARRIVAL_FAIL';

export const GET_PRODUCTS_BY_SOLD_OK = 'GET_PRODUCTS_BY_SOLD_OK';
export const GET_PRODUCTS_BY_SOLD_FAIL = 'GET_PRODUCTS_BY_SOLD_FAIL';

export const FILTER_PRODUCTS_OK = 'FILTER_PRODUCTS_OK';
export const FILTER_PRODUCTS_FAIL = 'FILTER_PRODUCTS_FAIL';


// Carrito Local (frontend)
export const ADD_ITEM = 'ADD_ITEM';

export const GET_TOTAL = 'GET_TOTAL';
export const GET_ITEM_TOTAL = 'GET_ITEM_TOTAL';
export const GET_ITEMS = 'GET_ITEMS';

export const UPDATE_ITEM = 'UPDATE_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const EMPTY_CART = 'EMPTY_CART';

// Cart (base de datos)
export const ADD_ITEM_OK = 'ADD_ITEM_OK';
export const ADD_ITEM_FAIL = 'ADD_ITEM_FAIL';

export const GET_TOTAL_OK = 'GET_TOTAL_OK';
export const GET_TOTAL_FAIL = 'GET_TOTAL_FAIL';

export const GET_ITEM_TOTAL_OK = 'GET_ITEM_TOTAL_OK';
export const GET_ITEM_TOTAL_FAIL = 'GET_ITEM_TOTAL_FAIL';

export const GET_ITEMS_OK = 'GET_ITEMS_OK';
export const GET_ITEMS_FAIL = 'GET_ITEMS_FAIL';

export const UPDATE_ITEM_OK = 'UPDATE_ITEM_OK';
export const UPDATE_ITEM_FAIL = 'UPDATE_ITEM_FAIL';

export const REMOVE_ITEM_OK = 'REMOVE_ITEM_OK';
export const REMOVE_ITEM_FAIL = 'REMOVE_ITEM_FAIL';

export const EMPTY_CART_OK= 'EMPTY_CART_OK';
export const EMPTY_CART_FAIL = 'EMPTY_CART_FAIL';

export const SYNCH_CART_OK = 'SYNCH_CART_OK';
export const SYNCH_CART_FAIL = 'SYNCH_CART_FAIL';


// Accounts
export const GET_ACCOUNT_OK = 'GET_ACCOUNT_OK';
export const GET_ACCOUNT_FAIL = 'GET_ACCOUNT_FAIL';

export const UPDATE_ACCOUNT_OK = 'UPDATE_ACCOUNT_OK';
export const UPDATE_ACCOUNT_FAIL = 'UPDATE_ACCOUNT_FAIL';


// Wishlist
export const GET_WISHLIST_ITEMS_OK = 'GET_WISHLIST_ITEMS_OK';
export const GET_WISHLIST_ITEMS_FAIL = 'GET_WISHLIST_ITEMS_FAIL';

export const ADD_WISHLIST_ITEM_OK = 'ADD_WISHLIST_ITEM_OK';
export const ADD_WISHLIST_ITEM_FAIL = 'ADD_WISHLIST_ITEM_FAIL';

export const GET_WISHLIST_ITEM_TOTAL_OK = 'GET_WISHLIST_ITEM_TOTAL_OK';
export const GET_WISHLIST_ITEM_TOTAL_FAIL = 'GET_WISHLIST_ITEM_TOTAL_FAIL';

export const REMOVE_WISHLIST_ITEM_OK = 'REMOVE_WISHLIST_ITEM_OK';
export const REMOVE_WISHLIST_ITEM_FAIL = 'REMOVE_WISHLIST_ITEM_FAIL';

export const CLEAR_WISHLIST = 'CLEAR_WISHLIST';


// Shipping
export const GET_SHIPPING_OPTIONS_OK = 'GET_SHIPPING_OPTIONS_OK';
export const GET_SHIPPING_OPTIONS_FAIL = 'GET_SHIPPING_OPTIONS_FAIL';


// Coupons
export const GET_COUPON_OK = 'GET_COUPON_OK';
export const GET_COUPON_FAIL = 'GET_COUPON_FAIL';


// Orders
export const GET_ORDERS_OK = 'GET_ORDERS_OK';
export const GET_ORDERS_FAIL = 'GET_ORDERS_FAIL';
export const GET_ORDER_DETAIL_OK = 'GET_ORDER_DETAIL_OK';
export const GET_ORDER_DETAIL_FAIL = 'GET_ORDER_DETAIL_FAIL';


//Payments
export const GET_PAYMENT_TOTAL_OK = 'GET_PAYMENT_TOTAL_OK';
export const GET_PAYMENT_TOTAL_FAIL = 'GET_PAYMENT_TOTAL_FAIL';
export const LOAD_BT_TOKEN_OK = 'LOAD_BT_TOKEN_OK';
export const LOAD_BT_TOKEN_FAIL = 'LOAD_BT_TOKEN_FAIL';
export const PAYMENT_OK = 'PAYMENT_OK';
export const PAYMENT_FAIL = 'PAYMENT_FAIL';
export const RESET_PAYMENT_INFO = 'RESET_PAYMENT_INFO';
export const SET_PAYMENT_LOADING = 'SET_PAYMENT_LOADING';
export const REMOVE_PAYMENT_LOADING = 'REMOVE_PAYMENT_LOADING';