// Authentication JWT 

export const SIGNUP_OK = 'SIGNUP_OK';
export const SIGNUP_FAIL = 'SIGNUP_SUCCESS';

export const LOGIN_OK = "LOGIN_OK"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const USER_LOADED_OK = "USER_LOADED_OK"
export const USER_LOADED_FAIL = "USER_LOADED_FAIL"

export const ACTIVATION_OK = "ACTIVATION_OK"
export const ACTIVATION_FAIL = "ACTIVATION_FAIL"

export const SET_AUTH_LOADING="SET_AUTH_LOADING"
export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';

export const AUTHENTICATED_OK = "AUTHENTICATED_OK"
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL"

export const REFRESH_OK = "REFRESH_OK"
export const REFRESH_FAIL = "REFRESH_FAIL"

export const LOGOUT = 'LOGOUT';

export const RESET_PASSWORD_OK="RESET_PASSWORD_OK"
export const RESET_PASSWORD_FAIL="RESET_PASSWORD_FAIL"

export const RESET_PASSWORD_CONFIRM_OK="RESET_PASSWORD_CONFIRM_OK"
export const RESET_PASSWORD_CONFIRM_FAIL="RESET_PASSWORD_CONFIRM_FAIL"

// Alerts

export const SET_ALERT="SET_ALERT"
export const REMOVE_ALERT="REMOVE_ALERT"


// Products 

export const GET_PRODUCT_OK = "GET_PRODUCT_OK"
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL"

export const GET_PRODUCTS_HOME_OK = "GET_PRODUCTS_HOME_OK"
export const GET_PRODUCTS_HOME_FAIL = "GET_PRODUCTS_HOME_FAIL"